/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileEditImport } from './routes/profile-edit'
import { Route as ProfileImport } from './routes/profile'
import { Route as IndexImport } from './routes/index'
import { Route as CharactersCharacterIdImport } from './routes/characters.$characterId'

// Create/Update Routes

const ProfileEditRoute = ProfileEditImport.update({
  id: '/profile-edit',
  path: '/profile-edit',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CharactersCharacterIdRoute = CharactersCharacterIdImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/profile-edit': {
      id: '/profile-edit'
      path: '/profile-edit'
      fullPath: '/profile-edit'
      preLoaderRoute: typeof ProfileEditImport
      parentRoute: typeof rootRoute
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/profile-edit': typeof ProfileEditRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/profile-edit': typeof ProfileEditRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/profile-edit': typeof ProfileEditRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/profile-edit' | '/characters/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/profile-edit' | '/characters/$characterId'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/profile-edit'
    | '/characters/$characterId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ProfileEditRoute: typeof ProfileEditRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ProfileEditRoute: ProfileEditRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/profile-edit",
        "/characters/$characterId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/profile-edit": {
      "filePath": "profile-edit.tsx"
    },
    "/characters/$characterId": {
      "filePath": "characters.$characterId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
